#pragma once

/**
 * @file ackermann_kinematics.h
 * @brief High-level Ackermann steering kinematics for firmware use.
 *
 * Builds on top of the autogenerated CAD lookup table (CAD/ackermann_lut.h)
 * and adds:
 *  - getRightWheelAngleLUT()  – missing from the autogenerated file
 *  - getTurnRadius()          – servo angle → turning radius (mm)
 *  - getServoAngleForRadius() – turning radius → servo angle (inversion)
 *
 * Design notes
 * ─────────────
 * • The autogenerated file (CAD/ackermann_lut.h) is produced by
 *   CAD/analyze_ackermann.py and must NEVER be edited by hand.
 *   All additions go here instead.
 *
 * • Kinematic wheelbase L = 127 mm, NOT the physical axle-to-axle gap of
 *   100 mm.  The pin-slot joint and tie-rod geometry push the effective
 *   turning-centre further back.  Back-calculation from the Fusion 360 sweep
 *   at servo = +40° confirms:
 *       R = L · (cot δ_inner + cot δ_outer) / 2 = 155.9 mm  ⟹  L = 127 mm
 *   (matches the empirical 154.6 mm measurement to within 0.8 %).
 *
 * • A 1.02× tire-slip factor is applied in getTurnRadius() to account for
 *   rubber deformation during cornering (documented in the kinematics report).
 *   Adjust TIRE_SLIP_FACTOR if you re-validate on a different surface.
 *
 * • Sign convention (matches existing set_steering() convention):
 *     servo_angle > 0  → right turn  → positive radius
 *     servo_angle < 0  → left  turn  → negative radius
 *     servo_angle = 0  → straight    → large magnitude radius (STRAIGHT_RADIUS)
 */

#include "../CAD/ackermann_lut.h"  // autogenerated LUT: LUT_LEFT[], LUT_RIGHT[], getLeftWheelAngleLUT()
#include <math.h>                  // fabsf, tanf, roundf

namespace Ackermann {

// ─────────────────────────────────────────────────────────────────────────────
// PHYSICAL CONSTANTS
// ─────────────────────────────────────────────────────────────────────────────

/// Kinematic wheelbase (mm). Derived from Fusion 360 CAD sweep; see file header.
constexpr float WHEELBASE_MM = 127.0f;

/// Tire slip compensation factor (rubber deformation in cornering).
constexpr float TIRE_SLIP_FACTOR = 1.02f;

/// Servo angles below this (degrees) are treated as "straight" in radius calcs.
constexpr float MIN_STEER_FOR_RADIUS_DEG = 2.0f;

/// Radius returned / accepted as "effectively straight" (mm).
constexpr float STRAIGHT_RADIUS_MM = 99999.0f;

/// Radius above this is clamped to 0° (straight) in getServoAngleForRadius().
constexpr float MAX_USEFUL_RADIUS_MM = 2000.0f;


// ─────────────────────────────────────────────────────────────────────────────
// MISSING LUT FUNCTION (autogenerated file only has getLeftWheelAngleLUT)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * @brief Returns the right-wheel steering angle (degrees) for a given servo
 *        angle, using the CAD lookup table with linear interpolation.
 *
 * Sign convention from the Fusion 360 sweep:
 *   servo > 0 → right turn → right wheel angle > 0° (toe-out inner)
 *   servo < 0 → left  turn → right wheel angle < 0°
 *
 * @param servoAngle Servo angle in degrees (clamped to ±50°).
 * @return Right-wheel angle in degrees.
 */
inline float getRightWheelAngleLUT(float servoAngle)
{
    float clamped = constrain(servoAngle, MIN_SERVO_DEG, MAX_SERVO_DEG);
    float index_f = (clamped - MIN_SERVO_DEG) / SERVO_STEP_DEG;
    int idx = (int)index_f;
    if (idx >= (int)TABLE_SIZE - 1) return LUT_RIGHT[TABLE_SIZE - 1];

    float fraction = index_f - idx;
    return LUT_RIGHT[idx] + fraction * (LUT_RIGHT[idx + 1] - LUT_RIGHT[idx]);
}


// ─────────────────────────────────────────────────────────────────────────────
// FORWARD MAP: servo angle → turning radius
// ─────────────────────────────────────────────────────────────────────────────

/**
 * @brief Computes the Ackermann turning radius for a given servo angle.
 *
 * Uses the average of both wheel angles (bicycle model approximation):
 *     R = WHEELBASE_MM / tan(avg_wheel_angle) × TIRE_SLIP_FACTOR
 *
 * Accuracy (from CAD validation, servo 15°–40°): ~2.35 % mean error.
 *
 * @param servoAngle Servo offset from centre in degrees.
 *                   Positive → right turn, negative → left turn.
 * @return Turning radius in mm.
 *         Positive → right turn, negative → left turn.
 *         Returns ±STRAIGHT_RADIUS_MM when |servoAngle| < MIN_STEER_FOR_RADIUS_DEG.
 */
inline float getTurnRadius(float servoAngle)
{
    if (fabsf(servoAngle) < MIN_STEER_FOR_RADIUS_DEG) {
        return (servoAngle >= 0.0f) ? STRAIGHT_RADIUS_MM : -STRAIGHT_RADIUS_MM;
    }

    float leftDeg  = getLeftWheelAngleLUT(servoAngle);
    float rightDeg = getRightWheelAngleLUT(servoAngle);

    // Average wheel angle (bicycle model).
    // At servo > 0 (right turn): left is outer (larger angle), right is inner (smaller).
    // Average gives the equivalent single-wheel steering angle.
    float avgDeg = (fabsf(leftDeg) + fabsf(rightDeg)) / 2.0f;
    float avgRad = avgDeg * (float)M_PI / 180.0f;

    if (avgRad < 0.001f) {
        return (servoAngle >= 0.0f) ? STRAIGHT_RADIUS_MM : -STRAIGHT_RADIUS_MM;
    }

    float radius = WHEELBASE_MM / tanf(avgRad) * TIRE_SLIP_FACTOR;

    // Preserve sign: positive servo → positive (right) radius
    return (servoAngle >= 0.0f) ? radius : -radius;
}


// ─────────────────────────────────────────────────────────────────────────────
// INVERSE MAP: turning radius → servo angle
// ─────────────────────────────────────────────────────────────────────────────

/**
 * @brief Finds the servo angle required to achieve a given turning radius.
 *
 * Uses a binary search over the LUT.  The search is monotonic between
 * MIN_STEER_FOR_RADIUS_DEG and MAX_SERVO_DEG so binary search is safe.
 *
 * @param radius_mm Desired turning radius in mm.
 *                  Positive → right turn, negative → left turn.
 *                  Values beyond ±MAX_USEFUL_RADIUS_MM return 0° (straight).
 * @return Servo angle in degrees (same sign convention as set_steering()).
 *         Clamped to ±MAX_SERVO_DEG.
 */
inline float getServoAngleForRadius(float radius_mm)
{
    // Straight-line guard
    if (fabsf(radius_mm) > MAX_USEFUL_RADIUS_MM || fabsf(radius_mm) < 1.0f) {
        return 0.0f;
    }

    float absRadius = fabsf(radius_mm);
    float sign = (radius_mm > 0.0f) ? 1.0f : -1.0f;

    // Binary search over [MIN_STEER_FOR_RADIUS_DEG, MAX_SERVO_DEG].
    // getTurnRadius() is monotonically DECREASING with |servo angle|:
    //   small servo → large radius, large servo → small radius.
    float lo = MIN_STEER_FOR_RADIUS_DEG;
    float hi = MAX_SERVO_DEG;

    // If the requested radius is larger than what the minimum servo achieves,
    // just return the minimum steering angle (effectively straight).
    float r_at_lo = getTurnRadius(lo);  // large radius
    float r_at_hi = getTurnRadius(hi);  // small radius

    if (absRadius > fabsf(r_at_lo)) return 0.0f;           // Radius too large → straight
    if (absRadius < fabsf(r_at_hi)) return sign * hi;      // Radius too small → max steer

    // Binary search: find angle where |getTurnRadius(angle)| ≈ absRadius
    for (int i = 0; i < 20; i++) {  // 20 iterations gives < 0.0001° precision
        float mid = (lo + hi) / 2.0f;
        float r_mid = fabsf(getTurnRadius(mid));

        if (r_mid > absRadius) {
            lo = mid;   // need larger angle to reduce radius
        } else {
            hi = mid;   // need smaller angle to increase radius
        }
    }

    float result = (lo + hi) / 2.0f;
    return sign * constrain(result, MIN_STEER_FOR_RADIUS_DEG, MAX_SERVO_DEG);
}

} // namespace Ackermann
